Repository Dulce-Work-Schedule/2018.1-Dulce_Hospital, pull requests merged in 2018-05, with the labels that each got.

#12 Fix #9 Refatorando o Readme e criando o guia de instalação.
  README.md
  guia_de_instalacao.md
Labels: 0-Devops, 1-Infraestrutura, 2-Integração Continua, 3-Task, 4-Planejado, 5-Iniciante

#13 Fix 1 2 4 7 8 10 ambiente
  .travis.yml
  Client/Dockerfile
  Client/client_hospital.js
  Client/package.json
  Docker/Dev/Client/Dockerfile
  Docker/Dev/Server/Dockerfile
  Docker/Dev/build.yml
  Docker/Dev/env/mongo.env
  Docker/Dev/env/rabbitmq.env
  Docker/Dev/start-deps.yml
  Docker/Dev/start-hospital.yml
  Docker/Prod/.keep
  Docker/Test/Client/Dockerfile
  Docker/Test/Server/Dockerfile
  Docker/Test/build.yml
  Docker/Test/env/.keep
  Docker/Test/start-hospital.yml
  Server/Dockerfile
  Server/_hospital.js
  Server/hospital.js
  Server/package.json
  Server/test/hospital.test.js
  docker-compose.yml
  utils/script_coveralls.sh
Labels: 0-Devops, 1-Infraestrutura, 2-Integração Continua, 4-Planejado, 5-Intermediário

#15 HOTFIX #1 arrumando package.json
  Client/client_hospital.js
  Client/package.json
  Docker/Dev/start-hospital.yml
  Server/hospital.js
  Server/package.json
Labels: 0-Devops, 1-Infraestrutura, 2-Integração Continua
