Repository Dulce-Work-Schedule/2018.1-Dulce_Hospital, pull requests merged in 2018-06, with the labels that each got.

#17 Fix #16 Finalizando correções nas nomeclaturas
  .travis.yml
  Environments/Development/Client/Dockerfile
  Environments/Development/Server/Dockerfile
  Environments/Development/Variables/mongo.env
  Environments/Development/Variables/rabbitmq.env
  Environments/Development/build.yml
  Environments/Development/start-deps.yml
  Environments/Development/start-hospital.yml
  Environments/Production/.keep
  Environments/Test/Client/Dockerfile
  Environments/Test/Server/Dockerfile
  Environments/Test/Variables/.keep
  Environments/Test/Variables/coveralls.env
  Environments/Test/build.yml
  Environments/Test/start-hospital.yml
  guia_de_instalacao.md
  utils/script_coveralls.sh
Labels: 0-Devops, 1-Viabilidade Técnica, 2-Integração Continua, 3-Task, 4-Adicionado, 5-Intermediário

#19 Fix #18 Finalizando ambiente e configurações de produção
  .travis.yml
  Environments/Production/.keep
  Environments/Production/Client/Dockerfile
  Environments/Production/Server/Dockerfile
  Environments/Production/build.yml
  utils/deploy.sh
Labels: 0-Devops, 1-Infraestrutura, 2-Integração Continua, 3-Task, 4-Adicionado, 5-Intermediário

#20 HOTFIX Corrigindo deploy.sh
  utils/deploy.sh
Labels: 0-Devops, 1-Infraestrutura, 2-Deploy Contínuo, 4-Adicionado, 5-Avançado
